### ISSUE TITLE
error: failed to load manifest for workspace memeber "/home/john/tcp-chat/backups/tcptest"

### ISSUE THREAD

**Issue by 2eppeli** [gatomod/tcp-chat#1]
Caused by:
    failed to read '/home/john/tcp-chat/backups/tcptest/Cargo.toml'

Caused by:
    No such file or directort(os error 2)

sorry, i am rust newbee.
this error occurs during the second step "cargo build --release -p server", and i don't know how to resolve it

**Comment by gatomod** [comment]
Whoops, I left a private test crate in the Cargo.toml workspaces. I'll fix it as soon as possible. Is just remove that crate from workspace members in the manifest. Thanks for open PR

**Comment by gatomod** [comment]
@JohnII7 fixed

**Comment by 2eppeli** [comment]
thank you, it works
